/**
 * TimestampType.java
 * <p>
 * File generated from the _0::TimestampType uml Class
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.wstrust.utility;

import org.w3c.dom.Document;
import org.w3c.dom.Node;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;

// End of user code


/**
 * Description of the class TimestampType.
 *
 *
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimestampType", propOrder = {
        "created",
        "expires",
        "id",
})
@XmlRootElement(name = "Timestamp")
public class TimestampType implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;


    /**
     *
     This element allows a creation time to be applied anywhere element wildcards are present.
     .
     */
    @XmlElement(name = "Created", namespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd")
    public String created;
    /**
     *
     This element allows an expiration time to be applied anywhere element wildcards are present.
     .
     */
    @XmlElement(name = "Expires", namespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd")
    public String expires;

	/*@XmlAnyElement
    public List<java.io.Serializable> group;*/
    /**
     *
     This global attribute supports annotating arbitrary elements with an String.
     .
     */
    @XmlAttribute(name = "Id", namespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd")
    public String id;

	/*@XmlAttribute(name = ":5")
	public List<java.io.Serializable> anyAttribute;*/

    /**
     * An attribute containing marshalled element node
     */
    @XmlTransient
    private Node _xmlNodePresentation;


    /**
     * Return created.
     * @return created :
    This element allows a creation time to be applied anywhere element wildcards are present.

    This element allows a creation time to be applied anywhere element wildcards are present.

    This element allows a creation time to be applied anywhere element wildcards are present.

    This element allows a creation time to be applied anywhere element wildcards are present.

    This element allows a creation time to be applied anywhere element wildcards are present.

     */
    public String getCreated() {
        return created;
    }

    /**
     * Set a value to attribute created.
     * @param created :
    This element allows a creation time to be applied anywhere element wildcards are present.

    This element allows a creation time to be applied anywhere element wildcards are present.

    This element allows a creation time to be applied anywhere element wildcards are present.

    This element allows a creation time to be applied anywhere element wildcards are present.

    This element allows a creation time to be applied anywhere element wildcards are present.
    .
     */
    public void setCreated(String created) {
        this.created = created;
    }


    /**
     * Return expires.
     * @return expires :
    This element allows an expiration time to be applied anywhere element wildcards are present.

    This element allows an expiration time to be applied anywhere element wildcards are present.

    This element allows an expiration time to be applied anywhere element wildcards are present.

    This element allows an expiration time to be applied anywhere element wildcards are present.

    This element allows an expiration time to be applied anywhere element wildcards are present.

     */
    public String getExpires() {
        return expires;
    }

    /**
     * Set a value to attribute expires.
     * @param expires :
    This element allows an expiration time to be applied anywhere element wildcards are present.

    This element allows an expiration time to be applied anywhere element wildcards are present.

    This element allows an expiration time to be applied anywhere element wildcards are present.

    This element allows an expiration time to be applied anywhere element wildcards are present.

    This element allows an expiration time to be applied anywhere element wildcards are present.
    .
     */
    public void setExpires(String expires) {
        this.expires = expires;
    }


    /**
     * Return group.
     * @return group
     *//*
	public List<java.io.Serializable> getGroup() {
		if (group == null) {
	        group = new ArrayList<java.io.Serializable>();
	    }
	    return group;
	}*/

    /**
     * Set a value to attribute group.
     * @param group.
     *//*
	public void setGroup(List<java.io.Serializable> group) {
	    this.group = group;
	}
	
	
	
	*//**
     * Add a group to the group collection.
     * @param group_elt Element to add.
     *//*
	public void addGroup(java.io.Serializable group_elt) {
	    this.getGroup().add(group_elt);
	}
	
	*//**
     * Remove a group to the group collection.
     * @param group_elt Element to remove
     *//*
	public void removeGroup(java.io.Serializable group_elt) {
	    this.getGroup().remove(group_elt);
	}
	*/

    /**
     * Return id.
     * @return id :
    This global attribute supports annotating arbitrary elements with an String.

    This global attribute supports annotating arbitrary elements with an String.

    This global attribute supports annotating arbitrary elements with an String.

    This global attribute supports annotating arbitrary elements with an String.

    This global attribute supports annotating arbitrary elements with an String.

     */
    public String getId() {
        return id;
    }

    /**
     * Set a value to attribute id.
     * @param id :
    This global attribute supports annotating arbitrary elements with an String.

    This global attribute supports annotating arbitrary elements with an String.

    This global attribute supports annotating arbitrary elements with an String.

    This global attribute supports annotating arbitrary elements with an String.

    This global attribute supports annotating arbitrary elements with an String.
    .
     */
    public void setId(String id) {
        this.id = id;
    }


    /**
     *
     * @return the extracted XML node from the document
     */
    public Node get_xmlNodePresentation() {
        if (_xmlNodePresentation == null) {
            JAXBContext jc;
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
            dbf.setNamespaceAware(true);
            DocumentBuilder db = null;
            Document doc = null;
            try {
                db = dbf.newDocumentBuilder();
                doc = db.newDocument();
            } catch (ParserConfigurationException e1) {
            }
            try {
                jc = JAXBContext.newInstance("net.ihe.gazelle.wstrust.utility");
                Marshaller m = jc.createMarshaller();
                m.marshal(this, doc);
                _xmlNodePresentation = doc.getElementsByTagNameNS(
                        "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd",
                        "Timestamp").item(0);
            } catch (JAXBException e) {
                try {
                    db = dbf.newDocumentBuilder();
                    _xmlNodePresentation = db.newDocument();
                } catch (Exception ee) {
                }
            }
        }
        return _xmlNodePresentation;
    }

    public void set_xmlNodePresentation(Node _xmlNodePresentation) {
        this._xmlNodePresentation = _xmlNodePresentation;
    }


}