/**
 * AppliesToType.java
 * <p>
 * File generated from the policy::AppliesToType uml Class
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.wstrust.policy;

import net.ihe.gazelle.wstrust.addressing.EndpointReferenceType;
import org.w3c.dom.Document;
import org.w3c.dom.Node;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;

// End of user code


/**
 * Description of the class AppliesToType.
 *
 * @author cel
 * @version $Id: $Id
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AppliesTo_._type", propOrder = {
        "endpointReference"
})
@XmlRootElement(name = "AppliesTo")
public class AppliesToType implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;


    @XmlElement(name = "EndpointReference", namespace = "http://www.w3.org/2005/08/addressing")
    public EndpointReferenceType endpointReference;


    /**
     * An attribute containing marshalled element node
     */
    @XmlTransient
    private Node _xmlNodePresentation;


    /**
     * <p>Getter for the field <code>endpointReference</code>.</p>
     *
     * @return a {@link net.ihe.gazelle.wstrust.addressing.EndpointReferenceType} object.
     */
    public EndpointReferenceType getEndpointReference() {
        return endpointReference;
    }

    /**
     * <p>Setter for the field <code>endpointReference</code>.</p>
     *
     * @param endpointReference a {@link net.ihe.gazelle.wstrust.addressing.EndpointReferenceType} object.
     */
    public void setEndpointReference(EndpointReferenceType endpointReference) {
        this.endpointReference = endpointReference;
    }

    /**
     * <p>Getter for the field <code>_xmlNodePresentation</code>.</p>
     *
     * @return a {@link org.w3c.dom.Node} object.
     */
    public Node get_xmlNodePresentation() {
        if (_xmlNodePresentation == null) {
            JAXBContext jc;
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
            dbf.setNamespaceAware(true);
            DocumentBuilder db = null;
            Document doc = null;
            try {
                db = dbf.newDocumentBuilder();
                doc = db.newDocument();
            } catch (ParserConfigurationException e1) {
            }
            try {
                jc = JAXBContext.newInstance("net.ihe.gazelle.wstrust.policy");
                Marshaller m = jc.createMarshaller();
                m.marshal(this, doc);
                _xmlNodePresentation = doc.getElementsByTagNameNS("http://www.w3.org/ns/ws-policy", "AppliesTo")
                        .item(0);
            } catch (JAXBException e) {
                try {
                    db = dbf.newDocumentBuilder();
                    _xmlNodePresentation = db.newDocument();
                } catch (Exception ee) {
                }
            }
        }
        return _xmlNodePresentation;
    }

    /**
     * <p>Setter for the field <code>_xmlNodePresentation</code>.</p>
     *
     * @param _xmlNodePresentation a {@link org.w3c.dom.Node} object.
     */
    public void set_xmlNodePresentation(Node _xmlNodePresentation) {
        this._xmlNodePresentation = _xmlNodePresentation;
    }


}
