/**
 * KeyTypeEnum.java
 * <p>
 * File generated from the _200512::KeyTypeEnum uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.wstrust.base;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Description of the enumeration KeyTypeEnum.
 *
 * @author cel
 * @version $Id: $Id
 */

@XmlType(name = "KeyTypeEnum")
@XmlEnum
@XmlRootElement(name = "KeyTypeEnum")
public enum KeyTypeEnum {
    @XmlEnumValue("http://docs.oasis-open.org/ws-sx/ws-trust/200512/PublicKey")
    HTTPDOCSOASISOPENORGWSSXWSTRUST200512PUBLICKEY("http://docs.oasis-open.org/ws-sx/ws-trust/200512/PublicKey"),
    @XmlEnumValue("http://docs.oasis-open.org/ws-sx/ws-trust/200512/SymmetricKey")
    HTTPDOCSOASISOPENORGWSSXWSTRUST200512SYMMETRICKEY("http://docs.oasis-open.org/ws-sx/ws-trust/200512/SymmetricKey"),
    @XmlEnumValue("http://docs.oasis-open.org/wssx/wstrust/200512/Bearer")
    HTTPDOCSOASISOPENORGWSSXWSTRUST200512BEARER("http://docs.oasis-open.org/wssx/wstrust/200512/Bearer");

    private final String value;

    KeyTypeEnum(String v) {
        value = v;
    }

    /**
     * <p>fromValue.</p>
     *
     * @param v a {@link java.lang.String} object.
     * @return a {@link net.ihe.gazelle.wstrust.base.KeyTypeEnum} object.
     */
    public static KeyTypeEnum fromValue(String v) {
        for (KeyTypeEnum c : KeyTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    /**
     * <p>value.</p>
     *
     * @return a {@link java.lang.String} object.
     */
    public String value() {
        return value;
    }

    /**
     * <p>Getter for the field <code>value</code>.</p>
     *
     * @return a {@link java.lang.String} object.
     */
    public String getValue() {
        return value;
    }

}
