/**
 * LifetimeType.java
 * <p>
 * File generated from the _200512::LifetimeType uml Class
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.wstrust.base;

// End of user code

import org.w3c.dom.Document;
import org.w3c.dom.Node;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;


/**
 * Description of the class LifetimeType.
 *
 * @author cel
 * @version $Id: $Id
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LifetimeType", propOrder = {
        "created",
        "expires"
})
@XmlRootElement(name = "Lifetime")
public class LifetimeType implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;


    /**
     *
     This element allows a creation time to be applied anywhere element wildcards are present.
     .
     */
    @XmlElement(name = "Created", namespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd")
    public String created;
    /**
     *
     This element allows an expiration time to be applied anywhere element wildcards are present.
     .
     */
    @XmlElement(name = "Expires", namespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd")
    public String expires;

    /**
     * An attribute containing marshalled element node
     */
    @XmlTransient
    private Node _xmlNodePresentation;


    /**
     * Return created.
     *
     * @return created :
     *    This element allows a creation time to be applied anywhere element wildcards are present.
     *
     *    This element allows a creation time to be applied anywhere element wildcards are present.
     *
     *    This element allows a creation time to be applied anywhere element wildcards are present.
     *
     *    This element allows a creation time to be applied anywhere element wildcards are present.
     */
    public String getCreated() {
        return created;
    }

    /**
     * Set a value to attribute created.
     *
     * @param created :
     *    This element allows a creation time to be applied anywhere element wildcards are present.
     *
     *    This element allows a creation time to be applied anywhere element wildcards are present.
     *
     *    This element allows a creation time to be applied anywhere element wildcards are present.
     *
     *    This element allows a creation time to be applied anywhere element wildcards are present.
     *    .
     */
    public void setCreated(String created) {
        this.created = created;
    }


    /**
     * Return expires.
     *
     * @return expires :
     *    This element allows an expiration time to be applied anywhere element wildcards are present.
     *
     *    This element allows an expiration time to be applied anywhere element wildcards are present.
     *
     *    This element allows an expiration time to be applied anywhere element wildcards are present.
     *
     *    This element allows an expiration time to be applied anywhere element wildcards are present.
     */
    public String getExpires() {
        return expires;
    }

    /**
     * Set a value to attribute expires.
     *
     * @param expires :
     *    This element allows an expiration time to be applied anywhere element wildcards are present.
     *
     *    This element allows an expiration time to be applied anywhere element wildcards are present.
     *
     *    This element allows an expiration time to be applied anywhere element wildcards are present.
     *
     *    This element allows an expiration time to be applied anywhere element wildcards are present.
     *    .
     */
    public void setExpires(String expires) {
        this.expires = expires;
    }


    /**
     * <p>Getter for the field <code>_xmlNodePresentation</code>.</p>
     *
     * @return a {@link org.w3c.dom.Node} object.
     */
    public Node get_xmlNodePresentation() {
        if (_xmlNodePresentation == null) {
            JAXBContext jc;
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
            dbf.setNamespaceAware(true);
            DocumentBuilder db = null;
            Document doc = null;
            try {
                db = dbf.newDocumentBuilder();
                doc = db.newDocument();
            } catch (ParserConfigurationException e1) {
            }
            try {
                jc = JAXBContext.newInstance("net.ihe.gazelle.wstrust.base");
                Marshaller m = jc.createMarshaller();
                m.marshal(this, doc);
                _xmlNodePresentation = doc
                        .getElementsByTagNameNS("http://docs.oasis-open.org/ws-sx/ws-trust/200512", "Lifetime").item(0);
            } catch (JAXBException e) {
                try {
                    db = dbf.newDocumentBuilder();
                    _xmlNodePresentation = db.newDocument();
                } catch (Exception ee) {
                }
            }
        }
        return _xmlNodePresentation;
    }

    /**
     * <p>Setter for the field <code>_xmlNodePresentation</code>.</p>
     *
     * @param _xmlNodePresentation a {@link org.w3c.dom.Node} object.
     */
    public void set_xmlNodePresentation(Node _xmlNodePresentation) {
        this._xmlNodePresentation = _xmlNodePresentation;
    }


}
