/**
 * RequestSecurityTokenType.java
 * <p>
 * File generated from the _200512::RequestSecurityTokenType uml Class
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.wstrust.base;

import net.ihe.gazelle.wstrust.policy.AppliesToType;
import org.w3c.dom.Document;
import org.w3c.dom.Node;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;

// End of user code


/**
 * Description of the class RequestSecurityTokenType.
 *
 * @author cel
 * @version $Id: $Id
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestSecurityTokenType", propOrder = {
        "requestType",
        "context", "appliesTo", "cancelTarget", "renewTarget", "validateTarget",
        "tokenType"
})
@XmlRootElement(name = "RequestSecurityToken")
public class RequestSecurityTokenType implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;


    @XmlElement(name = "RequestType", namespace = "http://docs.oasis-open.org/ws-sx/ws-trust/200512")
    public RequestTypeEnum requestType;
    @XmlElement(name = "TokenType", namespace = "http://docs.oasis-open.org/ws-sx/ws-trust/200512")
    public TokenTypeEnum tokenType;
    @XmlAttribute(name = "Context")
    public String context;
    @XmlElement(name = "AppliesTo", namespace = "http://www.w3.org/ns/ws-policy")
    public AppliesToType appliesTo;
    @XmlElement(name = "CancelTarget", namespace = "http://docs.oasis-open.org/ws-sx/ws-trust/200512")
    public CancelTargetType cancelTarget;
    @XmlElement(name = "RenewTarget", namespace = "http://docs.oasis-open.org/ws-sx/ws-trust/200512")
    public RenewTargetType renewTarget;
    @XmlElement(name = "ValidateTarget", namespace = "http://docs.oasis-open.org/ws-sx/ws-trust/200512")
    public ValidateTargetType validateTarget;

    /**
     * An attribute containing marshalled element node
     */
    @XmlTransient
    private Node _xmlNodePresentation;


    /**
     * Return context.
     *
     * @return context
     */
    public String getContext() {
        return context;
    }

    /**
     * Set a value to attribute context.
     *
     * @param context a {@link java.lang.String} object.
     */
    public void setContext(String context) {
        this.context = context;
    }

    /**
     * <p>Getter for the field <code>requestType</code>.</p>
     *
     * @return a {@link net.ihe.gazelle.wstrust.base.RequestTypeEnum} object.
     */
    public RequestTypeEnum getRequestType() {
        return requestType;
    }

    /**
     * <p>Setter for the field <code>requestType</code>.</p>
     *
     * @param requestType a {@link net.ihe.gazelle.wstrust.base.RequestTypeEnum} object.
     */
    public void setRequestType(RequestTypeEnum requestType) {
        this.requestType = requestType;
    }

    /**
     * <p>Getter for the field <code>tokenType</code>.</p>
     *
     * @return a {@link net.ihe.gazelle.wstrust.base.TokenTypeEnum} object.
     */
    public TokenTypeEnum getTokenType() {
        return tokenType;
    }

    /**
     * <p>Setter for the field <code>tokenType</code>.</p>
     *
     * @param tokenType a {@link net.ihe.gazelle.wstrust.base.TokenTypeEnum} object.
     */
    public void setTokenType(TokenTypeEnum tokenType) {
        this.tokenType = tokenType;
    }

    /**
     * <p>Getter for the field <code>appliesTo</code>.</p>
     *
     * @return a {@link net.ihe.gazelle.wstrust.policy.AppliesToType} object.
     */
    public AppliesToType getAppliesTo() {
        return appliesTo;
    }

    /**
     * <p>Setter for the field <code>appliesTo</code>.</p>
     *
     * @param appliesTo a {@link net.ihe.gazelle.wstrust.policy.AppliesToType} object.
     */
    public void setAppliesTo(AppliesToType appliesTo) {
        this.appliesTo = appliesTo;
    }

    /**
     * <p>Getter for the field <code>cancelTarget</code>.</p>
     *
     * @return a {@link net.ihe.gazelle.wstrust.base.CancelTargetType} object.
     */
    public CancelTargetType getCancelTarget() {
        return cancelTarget;
    }

    /**
     * <p>Setter for the field <code>cancelTarget</code>.</p>
     *
     * @param cancelTarget a {@link net.ihe.gazelle.wstrust.base.CancelTargetType} object.
     */
    public void setCancelTarget(CancelTargetType cancelTarget) {
        this.cancelTarget = cancelTarget;
    }

    /**
     * <p>Getter for the field <code>renewTarget</code>.</p>
     *
     * @return a {@link net.ihe.gazelle.wstrust.base.RenewTargetType} object.
     */
    public RenewTargetType getRenewTarget() {
        return renewTarget;
    }

    /**
     * <p>Setter for the field <code>renewTarget</code>.</p>
     *
     * @param renewTarget a {@link net.ihe.gazelle.wstrust.base.RenewTargetType} object.
     */
    public void setRenewTarget(RenewTargetType renewTarget) {
        this.renewTarget = renewTarget;
    }

    /**
     * <p>Getter for the field <code>validateTarget</code>.</p>
     *
     * @return a {@link net.ihe.gazelle.wstrust.base.ValidateTargetType} object.
     */
    public ValidateTargetType getValidateTarget() {
        return validateTarget;
    }

    /**
     * <p>Setter for the field <code>validateTarget</code>.</p>
     *
     * @param validateTarget a {@link net.ihe.gazelle.wstrust.base.ValidateTargetType} object.
     */
    public void setValidateTarget(ValidateTargetType validateTarget) {
        this.validateTarget = validateTarget;
    }

    /**
     * <p>Getter for the field <code>_xmlNodePresentation</code>.</p>
     *
     * @return a {@link org.w3c.dom.Node} object.
     */
    public Node get_xmlNodePresentation() {
        if (_xmlNodePresentation == null) {
            JAXBContext jc;
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
            dbf.setNamespaceAware(true);
            DocumentBuilder db = null;
            Document doc = null;
            try {
                db = dbf.newDocumentBuilder();
                doc = db.newDocument();
            } catch (ParserConfigurationException e1) {
            }
            try {
                jc = JAXBContext.newInstance("net.ihe.gazelle.wstrust.base");
                Marshaller m = jc.createMarshaller();
                m.marshal(this, doc);
                _xmlNodePresentation = doc.getElementsByTagNameNS("http://docs.oasis-open.org/ws-sx/ws-trust/200512",
                        "RequestSecurityToken").item(0);
            } catch (JAXBException e) {
                try {
                    db = dbf.newDocumentBuilder();
                    _xmlNodePresentation = db.newDocument();
                } catch (Exception ee) {
                }
            }
        }
        return _xmlNodePresentation;
    }

    /**
     * <p>Setter for the field <code>_xmlNodePresentation</code>.</p>
     *
     * @param _xmlNodePresentation a {@link org.w3c.dom.Node} object.
     */
    public void set_xmlNodePresentation(Node _xmlNodePresentation) {
        this._xmlNodePresentation = _xmlNodePresentation;
    }


}
