/**
 * RequestedReferenceType.java
 * <p>
 * File generated from the _200512::RequestedReferenceType uml Class
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.wstrust.base;

// End of user code

import net.ihe.gazelle.wstrust.secext.SecurityTokenReferenceType;
import org.w3c.dom.Document;
import org.w3c.dom.Node;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;


/**
 * Description of the class RequestedReferenceType.
 *
 * @author cel
 * @version $Id: $Id
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestedReferenceType", propOrder = {
        "securityTokenReference"
})
@XmlRootElement(name = "RequestedReferenceType")
public class RequestedReferenceType implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;


    /**
     * This element defines the wsse:SecurityTokenReference per Section 4.3..
     */
    @XmlElement(name = "SecurityTokenReference", required = true, namespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd")
    public SecurityTokenReferenceType securityTokenReference;

    /**
     * An attribute containing marshalled element node
     */
    @XmlTransient
    private Node _xmlNodePresentation;


    /**
     * Return securityTokenReference.
     *
     * @return securityTokenReference : This element defines the wsse:SecurityTokenReference per Section 4.3.This element defines the wsse:SecurityTokenReference per Section 4.3.This element defines the wsse:SecurityTokenReference per Section 4.3.This element defines the wsse:SecurityTokenReference per Section 4.3.
     */
    public SecurityTokenReferenceType getSecurityTokenReference() {
        return securityTokenReference;
    }

    /**
     * Set a value to attribute securityTokenReference.
     *
     * @param securityTokenReference : This element defines the wsse:SecurityTokenReference per Section 4.3.This element defines the wsse:SecurityTokenReference per Section 4.3.This element defines the wsse:SecurityTokenReference per Section 4.3.This element defines the wsse:SecurityTokenReference per Section 4.3..
     */
    public void setSecurityTokenReference(SecurityTokenReferenceType securityTokenReference) {
        this.securityTokenReference = securityTokenReference;
    }


    /**
     * <p>Getter for the field <code>_xmlNodePresentation</code>.</p>
     *
     * @return a {@link org.w3c.dom.Node} object.
     */
    public Node get_xmlNodePresentation() {
        if (_xmlNodePresentation == null) {
            JAXBContext jc;
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
            dbf.setNamespaceAware(true);
            DocumentBuilder db = null;
            Document doc = null;
            try {
                db = dbf.newDocumentBuilder();
                doc = db.newDocument();
            } catch (ParserConfigurationException e1) {
            }
            try {
                jc = JAXBContext.newInstance("net.ihe.gazelle.wstrust.base");
                Marshaller m = jc.createMarshaller();
                m.marshal(this, doc);
                _xmlNodePresentation = doc.getElementsByTagNameNS("http://docs.oasis-open.org/ws-sx/ws-trust/200512",
                        "RequestedReferenceType").item(0);
            } catch (JAXBException e) {
                try {
                    db = dbf.newDocumentBuilder();
                    _xmlNodePresentation = db.newDocument();
                } catch (Exception ee) {
                }
            }
        }
        return _xmlNodePresentation;
    }

    /**
     * <p>Setter for the field <code>_xmlNodePresentation</code>.</p>
     *
     * @param _xmlNodePresentation a {@link org.w3c.dom.Node} object.
     */
    public void set_xmlNodePresentation(Node _xmlNodePresentation) {
        this._xmlNodePresentation = _xmlNodePresentation;
    }


}
