/**
 * RequestTypeEnum.java
 * <p>
 * File generated from the _200512::RequestTypeEnum uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.wstrust.base;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;

/**
 * Description of the enumeration RequestTypeEnum.
 *
 * @author cel
 * @version $Id: $Id
 */

@XmlType(name = "RequestTypeEnum")
@XmlEnum
@XmlRootElement(name = "RequestType")
public enum RequestTypeEnum implements Serializable {
    @XmlEnumValue("http://docs.oasis-open.org/ws-sx/ws-trust/200512/Issue")
    ISSUE("http://docs.oasis-open.org/ws-sx/ws-trust/200512/Issue"),
    @XmlEnumValue("http://docs.oasis-open.org/ws-sx/ws-trust/200512/Renew")
    RENEW("http://docs.oasis-open.org/ws-sx/ws-trust/200512/Renew"),
    @XmlEnumValue("http://docs.oasis-open.org/ws-sx/ws-trust/200512/Cancel")
    CANCEL("http://docs.oasis-open.org/ws-sx/ws-trust/200512/Cancel"),
    @XmlEnumValue("http://docs.oasis-open.org/ws-sx/ws-trust/200512/STSCancel")
    STSCANCEL("http://docs.oasis-open.org/ws-sx/ws-trust/200512/STSCancel"),
    @XmlEnumValue("http://docs.oasis-open.org/ws-sx/ws-trust/200512/Validate")
    VALIDATE("http://docs.oasis-open.org/ws-sx/ws-trust/200512/Validate");

    private final String value;

    RequestTypeEnum(String v) {
        value = v;
    }

    /**
     * <p>fromValue.</p>
     *
     * @param v a {@link java.lang.String} object.
     * @return a {@link net.ihe.gazelle.wstrust.base.RequestTypeEnum} object.
     */
    public static RequestTypeEnum fromValue(String v) {
        for (RequestTypeEnum c : RequestTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    /**
     * <p>value.</p>
     *
     * @return a {@link java.lang.String} object.
     */
    public String value() {
        return value;
    }

    /**
     * <p>Getter for the field <code>value</code>.</p>
     *
     * @return a {@link java.lang.String} object.
     */
    public String getValue() {
        return value;
    }

}
