/**
 * RequestSecurityTokenResponseCollectionType.java
 * <p>
 * File generated from the _200512::RequestSecurityTokenResponseCollectionType uml Class
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.wstrust.base;

import org.w3c.dom.Document;
import org.w3c.dom.Node;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import java.util.ArrayList;
import java.util.List;

// End of user code


/**
 * Description of the class RequestSecurityTokenResponseCollectionType.
 *
 * @author cel
 * @version $Id: $Id
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestSecurityTokenResponseCollectionType", propOrder = {
        "requestSecurityTokenResponse"
})
@XmlRootElement(name = "RequestSecurityTokenResponseCollection")
public class RequestSecurityTokenResponseCollectionType implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;


    @XmlElement(name = "RequestSecurityTokenResponse", required = true, namespace = "http://docs.oasis-open.org/ws-sx/ws-trust/200512")
    public List<RequestSecurityTokenResponseType> requestSecurityTokenResponse;

    /**
     * An attribute containing marshalled element node
     */
    @XmlTransient
    private Node _xmlNodePresentation;


    /**
     * Return requestSecurityTokenResponse.
     *
     * @return requestSecurityTokenResponse
     */
    public List<RequestSecurityTokenResponseType> getRequestSecurityTokenResponse() {
        if (requestSecurityTokenResponse == null) {
            requestSecurityTokenResponse = new ArrayList<RequestSecurityTokenResponseType>();
        }
        return requestSecurityTokenResponse;
    }

    /**
     * Set a value to attribute requestSecurityTokenResponse.
     *
     * @param requestSecurityTokenResponse a {@link java.util.List} object.
     */
    public void setRequestSecurityTokenResponse(List<RequestSecurityTokenResponseType> requestSecurityTokenResponse) {
        this.requestSecurityTokenResponse = requestSecurityTokenResponse;
    }


    /**
     * Add a requestSecurityTokenResponse to the requestSecurityTokenResponse collection.
     *
     * @param requestSecurityTokenResponse_elt Element to add.
     */
    public void addRequestSecurityTokenResponse(RequestSecurityTokenResponseType requestSecurityTokenResponse_elt) {
        this.getRequestSecurityTokenResponse().add(requestSecurityTokenResponse_elt);
    }

    /**
     * Remove a requestSecurityTokenResponse to the requestSecurityTokenResponse collection.
     *
     * @param requestSecurityTokenResponse_elt Element to remove
     */
    public void removeRequestSecurityTokenResponse(RequestSecurityTokenResponseType requestSecurityTokenResponse_elt) {
        this.getRequestSecurityTokenResponse().remove(requestSecurityTokenResponse_elt);
    }


    /**
     * <p>Getter for the field <code>_xmlNodePresentation</code>.</p>
     *
     * @return a {@link org.w3c.dom.Node} object.
     */
    public Node get_xmlNodePresentation() {
        if (_xmlNodePresentation == null) {
            JAXBContext jc;
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
            dbf.setNamespaceAware(true);
            DocumentBuilder db = null;
            Document doc = null;
            try {
                db = dbf.newDocumentBuilder();
                doc = db.newDocument();
            } catch (ParserConfigurationException e1) {
            }
            try {
                jc = JAXBContext.newInstance("net.ihe.gazelle.wstrust.base");
                Marshaller m = jc.createMarshaller();
                m.marshal(this, doc);
                _xmlNodePresentation = doc.getElementsByTagNameNS("http://docs.oasis-open.org/ws-sx/ws-trust/200512",
                        "RequestSecurityTokenResponseCollectionType").item(0);
            } catch (JAXBException e) {
                try {
                    db = dbf.newDocumentBuilder();
                    _xmlNodePresentation = db.newDocument();
                } catch (Exception ee) {
                }
            }
        }
        return _xmlNodePresentation;
    }

    /**
     * <p>Setter for the field <code>_xmlNodePresentation</code>.</p>
     *
     * @param _xmlNodePresentation a {@link org.w3c.dom.Node} object.
     */
    public void set_xmlNodePresentation(Node _xmlNodePresentation) {
        this._xmlNodePresentation = _xmlNodePresentation;
    }


}
