/**
 * RequestSecurityTokenCollectionType.java
 * <p>
 * File generated from the _200512::RequestSecurityTokenCollectionType uml Class
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.wstrust.base;

import org.w3c.dom.Document;
import org.w3c.dom.Node;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import java.util.ArrayList;
import java.util.List;

// End of user code


/**
 * Description of the class RequestSecurityTokenCollectionType.
 *
 * @author cel
 * @version $Id: $Id
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestSecurityTokenCollectionType", propOrder = {
        "requestSecurityToken"
})
@XmlRootElement(name = "RequestSecurityTokenCollection")
public class RequestSecurityTokenCollectionType implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;


    @XmlElement(name = "RequestSecurityToken", namespace = "http://docs.oasis-open.org/ws-sx/ws-trust/200512")
    public List<RequestSecurityTokenType> requestSecurityToken;

    /**
     * An attribute containing marshalled element node
     */
    @XmlTransient
    private Node _xmlNodePresentation;


    /**
     * Return requestSecurityToken.
     *
     * @return requestSecurityToken
     */
    public List<RequestSecurityTokenType> getRequestSecurityToken() {
        if (requestSecurityToken == null) {
            requestSecurityToken = new ArrayList<RequestSecurityTokenType>();
        }
        return requestSecurityToken;
    }

    /**
     * Set a value to attribute requestSecurityToken.
     *
     * @param requestSecurityToken a {@link java.util.List} object.
     */
    public void setRequestSecurityToken(List<RequestSecurityTokenType> requestSecurityToken) {
        this.requestSecurityToken = requestSecurityToken;
    }


    /**
     * Add a requestSecurityToken to the requestSecurityToken collection.
     *
     * @param requestSecurityToken_elt Element to add.
     */
    public void addRequestSecurityToken(RequestSecurityTokenType requestSecurityToken_elt) {
        this.getRequestSecurityToken().add(requestSecurityToken_elt);
    }

    /**
     * Remove a requestSecurityToken to the requestSecurityToken collection.
     *
     * @param requestSecurityToken_elt Element to remove
     */
    public void removeRequestSecurityToken(RequestSecurityTokenType requestSecurityToken_elt) {
        this.getRequestSecurityToken().remove(requestSecurityToken_elt);
    }


    /**
     * <p>Getter for the field <code>_xmlNodePresentation</code>.</p>
     *
     * @return a {@link org.w3c.dom.Node} object.
     */
    public Node get_xmlNodePresentation() {
        if (_xmlNodePresentation == null) {
            JAXBContext jc;
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
            dbf.setNamespaceAware(true);
            DocumentBuilder db = null;
            Document doc = null;
            try {
                db = dbf.newDocumentBuilder();
                doc = db.newDocument();
            } catch (ParserConfigurationException e1) {
            }
            try {
                jc = JAXBContext.newInstance("net.ihe.gazelle.wstrust.base");
                Marshaller m = jc.createMarshaller();
                m.marshal(this, doc);
                _xmlNodePresentation = doc.getElementsByTagNameNS("http://docs.oasis-open.org/ws-sx/ws-trust/200512",
                        "RequestSecurityTokenCollection").item(0);
            } catch (JAXBException e) {
                try {
                    db = dbf.newDocumentBuilder();
                    _xmlNodePresentation = db.newDocument();
                } catch (Exception ee) {
                }
            }
        }
        return _xmlNodePresentation;
    }

    /**
     * <p>Setter for the field <code>_xmlNodePresentation</code>.</p>
     *
     * @param _xmlNodePresentation a {@link org.w3c.dom.Node} object.
     */
    public void set_xmlNodePresentation(Node _xmlNodePresentation) {
        this._xmlNodePresentation = _xmlNodePresentation;
    }


}
