/**
 * StatusCodeEnum.java
 * <p>
 * File generated from the _200512::StatusCodeEnum uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.wstrust.base;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Description of the enumeration StatusCodeEnum.
 *
 * @author cel
 * @version $Id: $Id
 */

@XmlType(name = "StatusCodeEnum")
@XmlEnum
@XmlRootElement(name = "StatusCodeEnum")
public enum StatusCodeEnum {
    @XmlEnumValue("http://docs.oasis-open.org/ws-sx/ws-trust/200512/status/valid")
    VALID("http://docs.oasis-open.org/ws-sx/ws-trust/200512/status/valid"),
    @XmlEnumValue("http://docs.oasis-open.org/ws-sx/ws-trust/200512/status/invalid")
    INVALID("http://docs.oasis-open.org/ws-sx/ws-trust/200512/status/invalid");

    private final String value;

    StatusCodeEnum(String v) {
        value = v;
    }

    /**
     * <p>fromValue.</p>
     *
     * @param v a {@link java.lang.String} object.
     * @return a {@link net.ihe.gazelle.wstrust.base.StatusCodeEnum} object.
     */
    public static StatusCodeEnum fromValue(String v) {
        for (StatusCodeEnum c : StatusCodeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    /**
     * <p>value.</p>
     *
     * @return a {@link java.lang.String} object.
     */
    public String value() {
        return value;
    }

    /**
     * <p>Getter for the field <code>value</code>.</p>
     *
     * @return a {@link java.lang.String} object.
     */
    public String getValue() {
        return value;
    }

}
