/**
 * StatusType.java
 * <p>
 * File generated from the _200512::StatusType uml Class
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.wstrust.base;

// End of user code

import org.w3c.dom.Document;
import org.w3c.dom.Node;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;


/**
 * Description of the class StatusType.
 *
 * @author cel
 * @version $Id: $Id
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatusType", propOrder = {
        "code",
        "reason"
})
@XmlRootElement(name = "Status")
public class StatusType implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;


    @XmlElement(name = "Code", required = true, namespace = "http://docs.oasis-open.org/ws-sx/ws-trust/200512")
    public StatusCodeEnum code;
    @XmlElement(name = "Reason", namespace = "http://docs.oasis-open.org/ws-sx/ws-trust/200512")
    public String reason;

    /**
     * An attribute containing marshalled element node
     */
    @XmlTransient
    private Node _xmlNodePresentation;


    /**
     * Return code.
     *
     * @return code
     */
    public StatusCodeEnum getCode() {
        return code;
    }

    /**
     * Set a value to attribute code.
     *
     * @param code a {@link net.ihe.gazelle.wstrust.base.StatusCodeEnum} object.
     */
    public void setCode(StatusCodeEnum code) {
        this.code = code;
    }


    /**
     * Return reason.
     *
     * @return reason
     */
    public String getReason() {
        return reason;
    }

    /**
     * Set a value to attribute reason.
     *
     * @param reason a {@link java.lang.String} object.
     */
    public void setReason(String reason) {
        this.reason = reason;
    }


    /**
     * <p>Getter for the field <code>_xmlNodePresentation</code>.</p>
     *
     * @return a {@link org.w3c.dom.Node} object.
     */
    public Node get_xmlNodePresentation() {
        if (_xmlNodePresentation == null) {
            JAXBContext jc;
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
            dbf.setNamespaceAware(true);
            DocumentBuilder db = null;
            Document doc = null;
            try {
                db = dbf.newDocumentBuilder();
                doc = db.newDocument();
            } catch (ParserConfigurationException e1) {
            }
            try {
                jc = JAXBContext.newInstance("net.ihe.gazelle.wstrust.base");
                Marshaller m = jc.createMarshaller();
                m.marshal(this, doc);
                _xmlNodePresentation = doc
                        .getElementsByTagNameNS("http://docs.oasis-open.org/ws-sx/ws-trust/200512", "Status").item(0);
            } catch (JAXBException e) {
                try {
                    db = dbf.newDocumentBuilder();
                    _xmlNodePresentation = db.newDocument();
                } catch (Exception ee) {
                }
            }
        }
        return _xmlNodePresentation;
    }

    /**
     * <p>Setter for the field <code>_xmlNodePresentation</code>.</p>
     *
     * @param _xmlNodePresentation a {@link org.w3c.dom.Node} object.
     */
    public void set_xmlNodePresentation(Node _xmlNodePresentation) {
        this._xmlNodePresentation = _xmlNodePresentation;
    }

}
