/**
 * RequestTypeEnum.java
 * <p>
 * File generated from the _200512::RequestTypeEnum uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.wstrust.base;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;

/**
 * Description of the enumeration RequestTypeEnum.
 *
 * @author cel
 * @version $Id: $Id
 */

@XmlType(name = "TokenTypeEnum")
@XmlEnum
@XmlRootElement(name = "TokenType")
public enum TokenTypeEnum implements Serializable {
    @XmlEnumValue("http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.1#SAMLV2.0")
    SAML20("http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.1#SAMLV2.0");

    private final String value;

    TokenTypeEnum(String v) {
        value = v;
    }

    /**
     * <p>fromValue.</p>
     *
     * @param v a {@link java.lang.String} object.
     * @return a {@link net.ihe.gazelle.wstrust.base.TokenTypeEnum} object.
     */
    public static TokenTypeEnum fromValue(String v) {
        for (TokenTypeEnum c : TokenTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    /**
     * <p>value.</p>
     *
     * @return a {@link java.lang.String} object.
     */
    public String value() {
        return value;
    }

    /**
     * <p>Getter for the field <code>value</code>.</p>
     *
     * @return a {@link java.lang.String} object.
     */
    public String getValue() {
        return value;
    }

}
