/**
 * SecurityTokenReferenceType.java
 * <p>
 * File generated from the _0::SecurityTokenReferenceType uml Class
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.wstrust.secext;

import org.w3c.dom.Document;
import org.w3c.dom.Node;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;

// End of user code


/**
 * Description of the class SecurityTokenReferenceType.
 *
 * @author cel
 * @version $Id: $Id
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SecurityTokenReferenceType", propOrder = {
        "id",
        "usage",
        "tokenType",
        "keyIdentifier"
})
@XmlRootElement(name = "SecurityTokenReference")
public class SecurityTokenReferenceType implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    /**
     *
     This global attribute supports annotating arbitrary elements with an String.
     .
     */
    @XmlAttribute(name = "Id", namespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd")
    public String id;
    /**
     * This global attribute is used to indicate the usage of a referenced or indicated token within the containing context.
     */
    @XmlAttribute(name = "Usage", namespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd")
    public String usage;
    @XmlAttribute(name = "TokenType", namespace = "http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd")
    public String tokenType;
    @XmlElement(name = "KeyIdentifier")
    private KeyIdentifier keyIdentifier;
    /**
     * An attribute containing marshalled element node
     */
    @XmlTransient
    private Node _xmlNodePresentation;

    /**
     * Return id.
     *
     * @return id :
     *    This global attribute supports annotating arbitrary elements with an String.
     */
    public String getId() {
        return id;
    }

    /**
     * Set a value to attribute id.
     *
     * @param id :
     *    This global attribute supports annotating arbitrary elements with an String.
     *
     *    .
     */
    public void setId(String id) {
        this.id = id;
    }


    /**
     * Return usage.
     *
     * @return usage : This global attribute is used to indicate the usage of a referenced or indicated token within the containing contextThis global attribute is used to indicate the usage of a referenced or indicated token within the containing contextThis global attribute is used to indicate the usage of a referenced or indicated token within the containing contextThis global attribute is used to indicate the usage of a referenced or indicated token within the containing context
     */
    public String getUsage() {
        return usage;
    }

    /**
     * Set a value to attribute usage.
     *
     * @param usage : This global attribute is used to indicate the usage of a referenced or indicated token within the containing contextThis global attribute is used to indicate the usage of a referenced or indicated token within the containing contextThis global attribute is used to indicate the usage of a referenced or indicated token within the containing contextThis global attribute is used to indicate the usage of a referenced or indicated token within the containing context.
     */
    public void setUsage(String usage) {
        this.usage = usage;
    }

    /**
     * <p>Getter for the field <code>keyIdentifier</code>.</p>
     *
     * @return a {@link net.ihe.gazelle.wstrust.secext.KeyIdentifier} object.
     */
    public KeyIdentifier getKeyIdentifier() {
        return keyIdentifier;
    }

    /**
     * <p>Setter for the field <code>keyIdentifier</code>.</p>
     *
     * @param keyIdentifier a {@link net.ihe.gazelle.wstrust.secext.KeyIdentifier} object.
     */
    public void setKeyIdentifier(KeyIdentifier keyIdentifier) {
        this.keyIdentifier = keyIdentifier;
    }

    /**
     * <p>Getter for the field <code>tokenType</code>.</p>
     *
     * @return a {@link java.lang.String} object.
     */
    public String getTokenType() {
        return tokenType;
    }

    /**
     * <p>Setter for the field <code>tokenType</code>.</p>
     *
     * @param tokenType a {@link java.lang.String} object.
     */
    public void setTokenType(String tokenType) {
        this.tokenType = tokenType;
    }

    /**
     * <p>Getter for the field <code>_xmlNodePresentation</code>.</p>
     *
     * @return a {@link org.w3c.dom.Node} object.
     */
    public Node get_xmlNodePresentation() {
        if (_xmlNodePresentation == null) {
            JAXBContext jc;
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
            dbf.setNamespaceAware(true);
            DocumentBuilder db = null;
            Document doc = null;
            try {
                db = dbf.newDocumentBuilder();
                doc = db.newDocument();
            } catch (ParserConfigurationException e1) {
            }
            try {
                jc = JAXBContext.newInstance("net.ihe.gazelle.wstrust.secext");
                Marshaller m = jc.createMarshaller();
                m.marshal(this, doc);
                _xmlNodePresentation = doc.getElementsByTagNameNS(
                        "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd",
                        "SecurityTokenReference").item(0);
            } catch (JAXBException e) {
                try {
                    db = dbf.newDocumentBuilder();
                    _xmlNodePresentation = db.newDocument();
                } catch (Exception ee) {
                }
            }
        }
        return _xmlNodePresentation;
    }

    /**
     * <p>Setter for the field <code>_xmlNodePresentation</code>.</p>
     *
     * @param _xmlNodePresentation a {@link org.w3c.dom.Node} object.
     */
    public void set_xmlNodePresentation(Node _xmlNodePresentation) {
        this._xmlNodePresentation = _xmlNodePresentation;
    }


}
